import React, { useState, useEffect } from 'react';
import BlogEntry from '../../Components/BlogEntries/BlogEntry';
import '../Blog/Blog.css';
import PatchNotes from '../../Data/PatchNotes';
import CustomTactics from '../../Data/CustomTactic';
import PackOpening from '../../Data/PackOpenings';

function Blog() {
  const [currentFilter, setCurrentFilter] = useState('PatchNotes');

  /*  An enum is used to filter through and display information according to which 
      Filter btn is clicked I cannot render all, because there is a bug that I am unable
      to figure out yet. When rendering all three filters, the images do not render with 
      them in some cases. I am assuming that it is just loading, and my WiFi is the issue
      but just to avoid poor UX, I only render one at a time.I have previously used enums
      in Unity C# but I have not used them in JS or React yet. My basic understanding was
      from https://www.geeksforgeeks.org/conditional-rendering-component-using-enums-in-reactjs. */

  // Function to render content based on currentFilter state
  const renderContent = () => {
    switch (currentFilter) {
      case 'PatchNotes':
        return <BlogEntry displayElements={PatchNotes} />; // Display Patch Notes
      case 'CustomTactics':
        return <BlogEntry displayElements={CustomTactics} />; // Display Custom Tactics
      case 'PackOpenings':
        return <BlogEntry displayElements={PackOpening} />; // Display Pack Openings 
      default:
        return <BlogEntry displayElements={PatchNotes} />; // Default to Patch Notes if unknown filter is selected
    }
  };

  // Function to handle filter button click
  const handleFilterClick = (filter) => {
    setCurrentFilter(filter); // Update the current filter state
    console.log(currentFilter)
  };



  return (
    <>
      <section className='blog-bg'></section>
      <section className="filter">
        {/* Button for Patch Notes with conditional 'active' class */}
        <button 
          className={`filter-btn ${currentFilter === 'PatchNotes' ? 'active' : ''}`}
          onClick={() => handleFilterClick('PatchNotes')}
        >
          Patch Notes
        </button>
        {/* Button for Custom Tactics */}
        <button
          className="filter-btn"
          onClick={() => setCurrentFilter('CustomTactics')}
        >
          Custom Tactics
        </button>
        {/* Button for Pack Openings */}
        <button
          className="filter-btn"
          onClick={() => setCurrentFilter('PackOpenings')}
        >
          Pack Openings
        </button>
      </section>
      <article className='content'>
        {/* This line of code was generated by ChatGPT. It converts 'camelCase 
            filter names' (Honestly, kind of confused on this still but will read
            into it more after) into a more readable format for the heading. I had an issue where my headings were
             not rendering or incorrectly rendering. This line of code fixed it*/}
        <h2 className='sub'>
          {currentFilter.replace(/([A-Z])/g, ' $1').trim()}
        </h2>
        {/* Section to display the content based on the current filter */}
        <section className='link-frame'>
          {renderContent()}
        </section>
      </article>
    </>
  );
}

export default Blog;
